### ISSUE TITLE
requirements.txt is missing django-rq-dashboard

### ISSUE THREAD

**Issue by Vitiell0** [spapas/django-test-rq#2]
After cloning the project I received "ImportError: No module named django_rq_dashboard"

Fixed with: pip install django-rq-dashboard

**Comment by spapas** [comment]
Thanks! Would you like to provide a small PR for this?

Best regards

**Comment by Vitiell0** [comment]
Just submitted one! Great work with the articles explaining django-rq, I found them super helpful

**Comment by spapas** [comment]
Thank you @Vitiell0 , have a happy new year!
